filter:
    excluded_paths:
        - 'tests/*'

build:
    tests:
        override:
            command: "php -v"
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

tools:
    external_code_coverage: true

checks:
    php: true

coding_style:
    php: true
